# Especifica la configuración de las funciones de Netlify
[build]
  publish = "dist"  # Directorio de salida de tu sitio (si usas un build tool como Webpack, Astro, etc.)
  functions = "netlify/functions"  # Carpeta donde están las funciones de Netlify

# Configuración de funciones
[functions]
  # Puedes especificar el "node_bundler" que usas (por ejemplo, esbuild)
  node_bundler = "esbuild"

  # Si necesitas cambiar el tiempo de espera de las funciones
  # max_duration = 10  # Duración máxima de ejecución de una función en segundos (por defecto es 10)

# Especifica las redirecciones (opcional, si las necesitas)
[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301

# Si tienes un sitio con un dominio propio
[context.production.environment]
  NODE_ENV = "production"